title: "Shiyu Liu's Homepage"
page-top-title: "Shiyu Liu's Homepage"
top-section-bg-text: "Be what you wanna be"
home-subtitle: "Shiyu Liu (刘诗雨)"
copyright-text: "&copy; Shiyu Liu 2023–2025. All Rights Reserved."
